### PR TITLE
Allows rubyzip >= 1.3.0 and fixes tests. Fixes #98

### LINKED ISSUE #98: Rubyzip 1.3 or 2.0
Please allow to use recent rubyzip

### PR DESCRIPTION
**Pull request by vtamara**

### CODE REVIEW

**Comment by vtamara** [comment]
Fixes #98

**Comment by jaredbeck** [comment]
Should this PR set `Zip.validate_entry_sizes = true` (per [instructions](https://github.com/rubyzip/rubyzip/pull/403)) or should that be the responsibility of our applications?

**Comment by vtamara** [comment]
In my projects I'm using rubyzip 2.0.0 where Zip.validate_entry_sizes is true by default.

I guess for 1.3.x it would be a good idea.  In what file of odf-report would you put `Zip.validate_entry_sizes = true` ?

**Comment by jaredbeck** [comment]
> In my projects I'm using rubyzip 2.0.0 where Zip.validate_entry_sizes is true by default.

Thanks Vladimir, I am using rubyzip 2.0.0 now (I am using your fork).

**Comment by sandrods** [comment]
sorry it took me so long. 
PR Merged. 
GEM Pushed.

Thanks!

**Comment by jaredbeck** [comment]
Thanks Sandro! Thanks Vladimir!

**Comment by vtamara** [comment]
Thanks .
Welcome.

**Pull request merged**
